<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <!-- Define template to match the root element -->
    <xsl:template match="/testsuite">
        <html>
            <head>
                <title>Test Report</title>
                <style>
                    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f0f2f5; color: #333; }
                    h1 { text-align: center; color: #4CAF50; margin-bottom: 20px; }
                    table { width: 90%; margin: 0 auto; border-collapse: collapse; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); }
                    th, td { padding: 12px; border: 1px solid #ddd; text-align: left; }
                    th { background-color: #4CAF50; color: white; }
                    tr:nth-child(even) { background-color: #f2f2f2; }
                    tr:hover { background-color: #f1f1f1; }
                    .pass { color: #4CAF50; font-weight: bold; }
                    .fail { color: #f44336; font-weight: bold; }
                    .footer { margin-top: 20px; text-align: center; font-size: 12px; color: #777; }
                    .status-icon {
                        font-size: 18px;
                        margin-right: 5px;
                    }
                    .pass .status-icon { color: #4CAF50; }
                    .fail .status-icon { color: #f44336; }
                </style>
            </head>
            <body>
                <h1>Test Report</h1>
                <table>
                    <tr>
                        <th>Status</th>
                        <th>Name</th>
                        <th>Time</th>
                        <th>Details</th>
                    </tr>
                    <!-- Iterate through each testcase -->
                    <xsl:for-each select="testcase">
                        <tr>
                            <!-- Display test case status -->
                            <td>
                                <xsl:choose>
                                    <xsl:when test="failure">
                                        <span class="status-icon">❌</span><span class="fail">Failed</span>
                                    </xsl:when>
                                    <xsl:otherwise>
                                        <span class="status-icon">✅</span><span class="pass">Passed</span>
                                    </xsl:otherwise>
                                </xsl:choose>
                            </td>
                            <!-- Display test case name -->
                            <td><xsl:value-of select="@name"/></td>
                            <!-- Display test case time -->
                            <td><xsl:value-of select="@time"/></td>
                            <!-- Display test case details, if available -->
                            <td>
                                <xsl:choose>
                                    <xsl:when test="failure">
                                        <xsl:value-of select="failure"/>
                                    </xsl:when>
                                    <xsl:otherwise>
                                        <xsl:text>No details available</xsl:text>
                                    </xsl:otherwise>
                                </xsl:choose>
                            </td>
                        </tr>
                    </xsl:for-each>
                </table>
                <div class="footer">
                    <p>Generated by SoapUI Automation Framework</p>
                </div>
            </body>
        </html>
    </xsl:template>

</xsl:stylesheet>